### ISSUE TITLE
Duplicate entries inserted

### ISSUE THREAD

**Issue by pviolette3** [gt-big-data/retina-crawler#20]
```
from rss_feed_parser import RssFeedParser
import feedparser
import time
from collections import Counter
resp = feedparser.parse('http://rss.cnn.com/rss/edition.rss')
links = [entry.link for entry in resp.entries]
print len(resp.entries), len(set(resp.entries)) # 109, 109
print len(links), len(set(links)) # 109 102 (!!)
print Counter(links).most_common(10) # Has one link with 3 entries, 5 with 2
```

The RSS Feed itself has entries that have duplicate links. The difference between the entries with the same links is published time. CNN is posting the same link to its RSS feed on each *update* of an article, not just the initial publication.

**Comment by supersam654** [comment]
Duplicate entries are no longer being added as multiple documents. Instead, the existing document gets updated and a list notes when the document was updated.
